services:
  rpi_imagegen:
    build:
      context: .
      dockerfile: container/Containerfile
    privileged: true
    stdin_open: true
    tty: true
    image: rpi-imagegen:latest
    working_dir: /home/imagegen/rpi-image-gen
    volumes:
      - ./_out:/home/imagegen/_out
      - ./recipes:/home/imagegen/recipes
